# Site settings
title: Bio-Commons
email: info@biocommons.org
description: "Bio-Commons"
baseurl: ""
url: "http://www.bio-commons.org/"
exclude: [README.md, Gemfile, Gemfile.lock, vendor]

# Build settings
markdown: kramdown
permalink: pretty

sass:
    style: :compressed

gems:
  - jekyll-redirect-from