# Site settings
title: Bio-Commons
email: info@biocommons.org
description: "Bio-Commons"
baseurl: ""
url: "http://www.biocommons.org"
exclude: [README.md, Gemfile, Gemfile.lock]

# Build settings
markdown: kramdown
permalink: pretty

sass:
    style: :compressed
